language: r
cache: packages
pandoc_version: 2.5

apt_packages:
  - libmagick++-dev
  - libcurl4-openssl-dev
  - libxml2-dev
  - jags

install:
  - Rscript -e 'install.packages("INLA", repos=c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/testing"), dep=TRUE)'

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
