---
title: "Materiais"
output:
  html_document:
    toc: false
---

## Materiais de consulta

- [Introdução à inferência
  bayesiana](http://www.leg.ufpr.br/~paulojus/CE227/InferenciaBayesiana.pdf).
  Apostila escrita por Stuart Coles, traduzida e adaptada por Paulo J.
  Ribeiro Jr.
- [Página com materiais do Prof Ricardo Ehlers (ICMC/USP)](http://www.icmc.usp.br/pessoas/ehlers/bayes/).
- Avaliações e provas anteriores: ver a seção "Materiais do curso" na
  [página da oferta
  enterior](http://www.leg.ufpr.br/doku.php/disciplinas:ce227-2018-01).

## Listas de exercícios

- [Lista de exercícios 1](exercicios/ex_intro.pdf)

## Slides utilizados nas aulas

- [Slides iniciais](oferta201902/CE227-Slides01.pdf)
- Slides sobre prioris e resumos da posteriori.
  [HTML](slides/CE227-Slides02.html). [PDF](slides/CE227-Slides02.pdf).

## Arquivos de comandos

- [Inferência sobre proporção](oferta201902/codigos/prop-paradigmas.R)
  - [arquivos auxiliar para obtenção de priori e posteriori no modelo binomial/beta](oferta201902/codigos/bayes-fun-01.R)
- [Comparação de duas amostras](oferta201902/codigos/duas-amostras-paradigmas.R)
  - [dados mandíbulas](oferta201902/dados/mandible.R)
  - [dados altura e peso](oferta201902/dados/alturapeso.csv)
  - [codigo para teste aleatorizado](oferta201902/codigos/mctest.R)
- [codigo aula 28/08 Exercício 2.1 a)](oferta201902/codigos/ExerciciosCap2.R)
